apiVersion: v1
kind: Namespace
metadata:
  name: factorio
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: factorio-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/factorio
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-pvc
  namespace: factorio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: factorio-pv

