services:
    prometheus:
        password: ENC[AES256_GCM,data:k48ZYb0mOrG4eq+uCcIvAAZWKse+hwjfHaiTK3TgW+nso22FtEpAVfUwYBSe2QveAr1gJ4YQ/n1Iz87cgjZDR2fSkgdPjXeoVChM/r2UJnX+rev25pCpDwlt6CDlorBCezDiEeBJJwkyZ+4ZL54XBca4H1dw3Du+ccMPang017HgeJIsPjOFh7uXC/ZRrAcc9G+5QBD6sWc=,iv:i+q3Rb7saG3rBHp4oBeIPyJQt807FixJ/gKvc5EZaC4=,tag:hi+m0bTH7sNwHF+7jj7tvw==,type:str]
scrape_hass: ENC[AES256_GCM,data:96qdrXrA372yEiC8Qk6aNAiTTJ57otQxpSCz8D8EsKeYEzA3Mn4oMF7tusrep8h7IlIqjhCyC/3A/NhMgAXKHIGh6SR0+zs73cmRtGC0D7nNPdLGC890PupQbVxAhQScreEQvx4pIY2RA8SU0UOYZOLSaTHKPDemRqSCxo4bAdwfPfFJ0m2vnmJ0M2anzYVpyqdY2ThdGj6UvjsVBzfLialarHUqzKwG7Q/muGYRjC7RCYvdi7VA,iv:MBYIj6KR4PG0E3As60Q8EXshe7VkwfGpzS3gNh75r8c=,tag:22Grj8osqUvhxmLvVIRVwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v8rg97r90ahd3z0y506n9nxmkr9ug65nf9ddqfde48hzug8glpqs43t0rv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbENweXl6aWJmNm5vbjdL
            ZEFmcGY2anhuWTM0YjVNZHRSb2tkai9TdFhZClNrbWI0eWNGM3lvRXZGZGs4QklT
            OFAzeEhCaXpZZzdNS2JCQXRBUkJGUTQKLS0tIEltT0JvQmYrdkl3cGRpQmFXMG80
            NWJCTzhZUlVQZW1sZi8rcW4zQmNXNlUKdwLgx66hUlN/7u5LyfjNOQx18caBcznG
            q+xrgiKlfvFH9mogf2a/mM8oOghV7re9HxEekJbDbFHQ8Xftv5eC3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tp36gvk5xgx7mr2kwsvmhyg9amamwsz2su0fkx3lw2nrej6jectsktuade
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVE1wSHVGUlJ2cWpPQVdu
            N2IvTmxyd3grRVZBM3hESGcvQXI1djJneHlVCkpyTUtBREQxbmtDN1dOTUsraFdJ
            T0Fna1I3UHoyUWVMWmJoLzUydTUyYTgKLS0tIFFOb3FadnJCVWFlakxXSEpwVURo
            R3VrbzYrMy93OWJwNEFvY0ZqRlNNbEkK14cOKwEJL04WpJOE793W8oZe0xtRW/T5
            XEPx/JZy6AmYRrqbDFBT0sfFPCj+S33HnNyuesSf+vg4NBRWte9xEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-28T12:16:07Z"
    mac: ENC[AES256_GCM,data:JkBjsYVrhsAY0/KyCWPLcACZ4aVSaxgBSkHAAJCJOmPe4XDa9xRVO8ssy8igAHvK0itMChdGVkTWKRK5vAtWLkVkAS3FicriLMfAiU9YLwIwrKIOVdbad90IonCyFoHSc7+Z+shP/Mm9dY/5hcgkEGYbb5P8dvyTgxzXXTNzKcc=,iv:TepaPvG2MP5+fdUbbSBLWj5Ko7YwvFa3t10d8SYhStQ=,tag:Fm72FCX1xiysxRQVnEwpXg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
