---
name: Schedule - Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: false
        required: false
        type: boolean
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json5"
      - ".github/workflows/schedule-renovate.yaml"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.5
        with:
          configurationFile: ".github/renovate.json5"
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
